swipe:
  3:
    left:
      # sendkey: "LEFTALT+RIGHT" # history back
      sendkey: "FORWARD" # history back
      keypress:
        LEFTCTRL:
          sendkey: "PREVIOUSSONG"

    right:
      # sendkey: "LEFTALT+LEFT" # history forward
      sendkey: "BACK" # history back
      keypress:
        LEFTCTRL:
          sendkey: "NEXTSONG"

    up:
      sendkey: "LEFTMETA" # Overview
      keypress:
        LEFTCTRL:
          sendkey: "BRIGHTNESSUP"
    down:
      sendkey: "LEFTMETA" # Overview
      keypress:
        LEFTCTRL:
          sendkey: 'BRIGHTNESSDOWN'

  4:
    left:
      update:
        sendkey: "VOLUMEDOWN"
    right:
      update:
        sendkey: "VOLUMEUP"
        
pinch:
  in:
    # sendkey: "ZOOMIN" # Zoom in
    sendkey: "LEFTCTRL+KPPLUS" # Zoom in
  out:
    # sendkey: "ZOOMOUT" # Zoom out
    sendkey: "LEFTCTRL+KPMINUS" # Zoom out


threshold:
  swipe: 0.2
  pinch: 0.8

interval:
  swipe: 0.8
  pinch: 1.5
  tap: 0.2

tap:
  1:
    command: "echo ----------------tap1----------------------------"
  # 2:
  #   command: "echo ----------------tap2----------------------------"
  # 3:
    # command: "echo ----------------tap3----------------------------"
  4:
    sendkey: "PLAYPAUSE"

hold:
#   1:
#     command: "echo ----------------hold1----------------------------"
#   2:
#     command: "echo ----------------hold2----------------------------"
#   3:
#     command: "echo ----------------hold3----------------------------"
  4:
    sendkey: "PLAYPAUSE"

plugin:
  inputs:
    libinput_command_input:
      enable-tap: true
      verbose: true
      show-keycodes: true
